- name: variables
  hosts: localhost
  vars:
    course: devops
    trainer: sivakumar
  tasks: 
  - name: override the variables
    ansible.builtin.debug:
     msg: "hello iam learing {{course}} from {{trainer}}"

  - name: print the variables
    ansible.builtin.debug:
      msg: "hello iam learing {{course}} from {{trainer}}"  